# Generated by Django 4.2.28 on 2026-02-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_author_id_alter_book_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacture_city', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
            ],
        ),
    ]
